// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Get DATABASE_URL from environment
const databaseUrl = process.env["DATABASE_URL"];
const vercelPostgresUrl = process.env["POSTGRES_PRISMA_URL"];

// Prefer DATABASE_URL whenever it's set (e.g. Supabase). Vercel may inject
// POSTGRES_PRISMA_URL automatically, which can accidentally override the
// intended database.
const finalDatabaseUrl = databaseUrl || vercelPostgresUrl;

// Only throw error if we're on Vercel or in production build
const isVercel = process.env.VERCEL === "1";
const isCI = process.env.CI === "true";

if (!finalDatabaseUrl && (isVercel || isCI)) {
  throw new Error(
    "DATABASE_URL or POSTGRES_PRISMA_URL environment variable is required.\n" +
    "For Vercel: These are automatically set when you create a Postgres database.\n" +
    "If missing, check: Vercel Dashboard → Storage → Postgres → Ensure database exists\n" +
    "Or manually set DATABASE_URL to your PostgreSQL connection string."
  );
}

// Use a dummy URL for local schema validation if not set (won't be used for actual DB operations)
// Must be PostgreSQL format for schema validation
const urlForConfig = finalDatabaseUrl || "postgresql://user:pass@localhost:5432/db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: urlForConfig,
  },
});
